

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rookk
 */
public class Compra extends javax.swing.JFrame {
    Connection conex=null;
    Statement stm=null;
    Menu m;
    /**
     * Creates new form Compra
     */
    public Compra(){
        initComponents();
    }
    
    public Compra(Menu menu) {
        initComponents();
        fecha();
        conectar();
        mostrarTablaComp();
        llenaCombo();
        this.m=menu;
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        
    }
    
    private void fecha(){

        Calendar cal= new GregorianCalendar();

        int day= cal.get(Calendar.DAY_OF_MONTH);
        int month= cal.get(Calendar.MONTH)+1;
        int year= cal.get(Calendar.YEAR);

        lblFechaD.setText(year+"-"+month+"-"+day);

    }
    public final void conectar(){
        String url= "jdbc:mysql://localhost:3306/ttdb";
        String Usuario= "root";
        String Pass= "123456";
        try{
            conex=DriverManager.getConnection(url,Usuario,Pass);
        }catch (Exception ex){
            System.out.println(ex);
        }
    }
    
    public void mostrarTablaComp(){
        try{
            stm=conex.createStatement();
            jtCompras.removeAll();
            ResultSet rs = stm.executeQuery("select adquisicion_item.fecha , adquisicion_item.nom_prov , item.nombre , adquisicion_item.cantidad, adquisicion_item.precio_unit, adquisicion_item.precio_total FROM adquisicion_item INNER JOIN item ON adquisicion_item.Item_cod_item = item.cod_item");
            
            DefaultTableModel mod =(DefaultTableModel)jtCompras.getModel();
            mod.setRowCount(0);
            while(rs.next()){
                Object data[]={rs.getString("fecha"),rs.getString("nom_prov"),rs.getString("nombre"),rs.getString("cantidad"),rs.getString("precio_unit"),rs.getString("precio_total")};
                mod.addRow(data);
                
            }
            
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex,"conexion",3);
        }
    }
    
    public void llenaCombo(){
        try{    
            cmbItem.removeAllItems();
            stm=conex.createStatement();
            ResultSet lista = stm.executeQuery("select nombre from item");

            while (lista.next()){
                cmbItem.addItem(lista.getString(1));
            }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,ex,"conexion",3);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtCompras = new javax.swing.JTable();
        cmdAñadir = new javax.swing.JButton();
        cmdEliminar = new javax.swing.JButton();
        cmbItem = new javax.swing.JComboBox<>();
        lblItem = new javax.swing.JLabel();
        lblProv = new javax.swing.JLabel();
        txtProv = new javax.swing.JTextField();
        lblCant = new javax.swing.JLabel();
        txtCant = new javax.swing.JTextField();
        lblPU7 = new javax.swing.JLabel();
        txtPU = new javax.swing.JTextField();
        lblFecha = new javax.swing.JLabel();
        lblFechaD = new javax.swing.JLabel();
        cmdVovler = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jtCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"2020-07-21", "Servicios s.a", "Tenedor", "10", "1", "10"}
            },
            new String [] {
                "Fecha", "Nombre Proveedor", "Item", "Cantidad", "Precio Unit", "Precio Total"
            }
        ));
        jtCompras.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jtCompras);
        if (jtCompras.getColumnModel().getColumnCount() > 0) {
            jtCompras.getColumnModel().getColumn(0).setResizable(false);
            jtCompras.getColumnModel().getColumn(1).setResizable(false);
            jtCompras.getColumnModel().getColumn(2).setResizable(false);
            jtCompras.getColumnModel().getColumn(3).setResizable(false);
            jtCompras.getColumnModel().getColumn(4).setResizable(false);
            jtCompras.getColumnModel().getColumn(5).setResizable(false);
        }

        cmdAñadir.setText("Añadir");
        cmdAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAñadirActionPerformed(evt);
            }
        });

        cmdEliminar.setText("Eliminar");
        cmdEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEliminarActionPerformed(evt);
            }
        });

        cmbItem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tenedor", "Item 2", "Item 3", "Item 4" }));

        lblItem.setText("Item:");

        lblProv.setText("Nombre del Proveedor:");

        txtProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProvActionPerformed(evt);
            }
        });
        txtProv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtProvKeyTyped(evt);
            }
        });

        lblCant.setText("Cantidad:");

        txtCant.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantKeyTyped(evt);
            }
        });

        lblPU7.setText("Precio Unitario:");

        txtPU.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPUKeyTyped(evt);
            }
        });

        lblFecha.setText("Fecha:");

        cmdVovler.setText("Volver");
        cmdVovler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdVovlerActionPerformed(evt);
            }
        });

        jLabel1.setText("$");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblItem)
                                .addGap(95, 95, 95)
                                .addComponent(cmbItem, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblProv)
                                    .addComponent(lblCant)
                                    .addComponent(lblPU7)
                                    .addComponent(lblFecha))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCant)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblFechaD)
                                            .addComponent(txtProv, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtPU)))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(136, 136, 136)
                        .addComponent(cmdAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmdEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                            .addComponent(cmdVovler, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(6, 6, 6)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblItem))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblProv)
                            .addComponent(txtProv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCant)
                            .addComponent(txtCant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPU7)
                            .addComponent(txtPU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFecha)
                            .addComponent(lblFechaD))
                        .addGap(0, 18, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmdEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmdAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(cmdVovler, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAñadirActionPerformed
        String f= lblFechaD.getText();
        String np = txtProv.getText();
        String ni = cmbItem.getSelectedItem().toString();
        String ci = "";
        String can= txtCant.getText();
        String pu = txtPU.getText();
        
        int total;
        total = Integer.parseInt(can) * Integer.parseInt(pu);
        try{    
            stm=conex.createStatement();
            ResultSet rs = stm.executeQuery("select cod_item from item where nombre='"+ ni +"'");
            rs.next();
            ci= rs.getString(1);
            
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,ex,"conexion",3);
        }
        try{
            stm=conex.createStatement();
            stm.executeUpdate("insert into adquisicion_item values('"+f+"','"+np+"',"+ci+","+can+","+pu+","+total+")");
            stm.executeUpdate("update item set cantidad_real=cantidad_real + "+can+" where item.cod_item="+ci+"  ");
            JOptionPane.showMessageDialog(null,"Añadido Correctamente\nLa cantidad real del item se ha actualizado","conexion",3);
            mostrarTablaComp();
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,ex,"conexion",3);
        }
    }//GEN-LAST:event_cmdAñadirActionPerformed

    private void cmdEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEliminarActionPerformed
        int index = jtCompras.getSelectedRow();
        if (index<0){
            JOptionPane.showMessageDialog(null, "Seleccione una Comrpa","conexion",3);
        }else{
            switch (JOptionPane.showConfirmDialog(null, "Seguro desea ELIMINAR esta Compra?","confirmacion",2)){
                case 0:
                    DefaultTableModel mod =(DefaultTableModel)jtCompras.getModel();
                    String f = mod.getValueAt(index, 0).toString();
                    String np = mod.getValueAt(index, 1).toString();
                    String cod = mod.getValueAt(index, 2).toString();
                    try{    
                        stm=conex.createStatement();
                        ResultSet rs = stm.executeQuery("select cod_item from item where nombre='"+ cod +"'");
                        rs.next();
                        cod= rs.getString(1);

                    }catch(SQLException ex){
                        JOptionPane.showMessageDialog(null,ex,"conexion",3);
                    }
                    String sql= "delete from adquisicion_item where fecha='"+f+"' and nom_prov='"+np+"' and Item_cod_item="+cod;
                    System.out.println(sql);

                    try{
                        stm=conex.createStatement();
                        stm.executeUpdate(sql);
                        JOptionPane.showMessageDialog(null, "Eliminado Correctamente","conexion",3);
                        jtCompras.clearSelection();
                        mostrarTablaComp();
                    }catch(SQLException ex){
                        JOptionPane.showMessageDialog(null, ex,"conexion",3);
                    }
                default:
                    break;
            }
            
        }
    }//GEN-LAST:event_cmdEliminarActionPerformed

    private void cmdVovlerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdVovlerActionPerformed
        m.setEnabled(true);
        dispose();
    }//GEN-LAST:event_cmdVovlerActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        m.setEnabled(true);
    }//GEN-LAST:event_formWindowClosing

    private void txtProvKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProvKeyTyped
        char C = evt.getKeyChar();
        if (!(Character.isAlphabetic(C)||Character.isSpaceChar(C))){
            evt.consume();
        }
    }//GEN-LAST:event_txtProvKeyTyped

    private void txtCantKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantKeyTyped
        char C = evt.getKeyChar();
        if (!(Character.isDigit(C))){
            evt.consume();
        }
    }//GEN-LAST:event_txtCantKeyTyped

    private void txtPUKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPUKeyTyped
        char C = evt.getKeyChar();
        if (!(Character.isDigit(C))){
            evt.consume();
        }
    }//GEN-LAST:event_txtPUKeyTyped

    private void txtProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProvActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Compra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Compra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbItem;
    private javax.swing.JButton cmdAñadir;
    private javax.swing.JButton cmdEliminar;
    private javax.swing.JButton cmdVovler;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtCompras;
    private javax.swing.JLabel lblCant;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFechaD;
    private javax.swing.JLabel lblItem;
    private javax.swing.JLabel lblPU7;
    private javax.swing.JLabel lblProv;
    private javax.swing.JTextField txtCant;
    private javax.swing.JTextField txtPU;
    private javax.swing.JTextField txtProv;
    // End of variables declaration//GEN-END:variables
}
