/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
/**
 *
 * @author Rookk
 */
public class Emp extends javax.swing.JFrame {
    Connection conex=null;
    Statement stm=null;
    int modo=0;
    /**
     * Creates new form Emp
     */
    public Emp() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }
    private Menu m;
    public Emp(Menu m){
        conectar();
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        this.m = m;
        llenaCombo();
        modo=1;
        
    }
    
    public Emp(Menu m, String r,String c,String n,String t,String f,String e,String he,String hs){
        conectar();
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        this.txtRut.setText(r);
        llenaCombo();
        this.cmbEmpleo.setSelectedItem(c);
        this.txtNombre.setText(n);
        if (t.equals("Empleado")){
            this.rbtEmp.setSelected(true);
        }else{
            this.rbtAdmin.setSelected(true);
        }
        this.txtFono.setText(f);
        this.txtEmail.setText(e);
        this.txtHE.setText(he);
        this.txtHS.setText(hs);

        this.txtRut.setEditable(false);
        this.m= m;
        modo=2;
    }
    public final void conectar(){
        String url= "jdbc:mysql://localhost:3306/ttdb";
        String Usuario= "root";
        String Pass= "123456";
        try{
            conex=DriverManager.getConnection(url,Usuario,Pass);
        }catch (Exception ex){
            JOptionPane.showMessageDialog(null,ex,"conexion",3);
        }
    }
    private void llenaCombo(){
        rbtEmp.setSelected(true);
        try{    
            cmbEmpleo.removeAllItems();
            stm=conex.createStatement();
            ResultSet lista = stm.executeQuery("select nom_empleo from empleo");

            while (lista.next()){
                cmbEmpleo.addItem(lista.getString(1));
            }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,ex,"conexion",3);
    }}
    
    public static Boolean validaRut ( String rut ) {
	Pattern pattern = Pattern.compile("^[0-9]+-[0-9kK]{1}$");
	Matcher matcher = pattern.matcher(rut);
	if ( matcher.matches() == false ) return false;
	String[] stringRut = rut.split("-");
	return stringRut[1].toLowerCase().equals(dv(stringRut[0]));
    }
    public static String dv ( String rut ) {
	Integer M=0,S=1,T=Integer.parseInt(rut);
	for (;T!=0;T=(int) Math.floor(T/=10))
		S=(S+T%10*(9-M++%6))%11;
	return ( S > 0 ) ? String.valueOf(S-1) : "k";		
    }
    public static Boolean validarMail(String mail){
        Pattern pattern = Pattern.compile("^\\w+([\\.-]?\\w+)*@\\w+([\\.-]?\\w+)*(\\.\\w{2,3})+$");
        Matcher matcher = pattern.matcher(mail);
        return matcher.matches();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblBombre = new javax.swing.JLabel();
        lblRut = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        lblContacto = new javax.swing.JLabel();
        lblFono = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        rbtAdmin = new javax.swing.JRadioButton();
        rbtEmp = new javax.swing.JRadioButton();
        txtEmail = new javax.swing.JTextField();
        cmdCancelar = new javax.swing.JButton();
        cmdSubmit = new javax.swing.JButton();
        lblEmpleo = new javax.swing.JLabel();
        cmbEmpleo = new javax.swing.JComboBox<>();
        lblHe = new javax.swing.JLabel();
        lblHs = new javax.swing.JLabel();
        txtRut = new javax.swing.JTextField();
        txtHE = new javax.swing.JFormattedTextField();
        txtHS = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        txtFono = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblBombre.setText("Nombre: ");

        lblRut.setText("Rut: ");

        lblTipo.setText("Tipo");

        lblContacto.setText("Contacto: ");

        lblFono.setText("Fono: ");

        lblEmail.setText("E-mail: ");

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        buttonGroup1.add(rbtAdmin);
        rbtAdmin.setSelected(true);
        rbtAdmin.setText("Administrador");

        buttonGroup1.add(rbtEmp);
        rbtEmp.setText("Empleado");

        cmdCancelar.setText("Cancelar");
        cmdCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCancelarActionPerformed(evt);
            }
        });

        cmdSubmit.setText("Ingresar");
        cmdSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSubmitActionPerformed(evt);
            }
        });

        lblEmpleo.setText("Empleo:");

        cmbEmpleo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblHe.setText("Hora Entrada:");

        lblHs.setText("Hora Salida:");

        txtHE.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));

        txtHS.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));

        jLabel1.setText("Hora:minutos");

        try {
            txtFono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("+569########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel2.setText("*con - verificador");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblBombre)
                                .addGap(25, 25, 25)
                                .addComponent(txtNombre))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRut)
                                    .addComponent(lblEmpleo))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbEmpleo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtRut)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblContacto)
                                            .addComponent(lblTipo))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rbtAdmin)
                                            .addComponent(rbtEmp)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(lblEmail)
                                                    .addComponent(lblFono))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                                    .addComponent(txtFono)))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblHe)
                                            .addComponent(lblHs))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtHE, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                            .addComponent(txtHS)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cmdSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cmdCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(34, 34, 34))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRut)
                    .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jLabel2)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmpleo)
                    .addComponent(cmbEmpleo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipo)
                    .addComponent(rbtAdmin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtEmp)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContacto)
                    .addComponent(lblFono)
                    .addComponent(txtFono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHe)
                    .addComponent(txtHE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHs)
                    .addComponent(txtHS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCancelarActionPerformed
        m.setEnabled(true);
        dispose();
    }//GEN-LAST:event_cmdCancelarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        m.setEnabled(true);
    }//GEN-LAST:event_formWindowClosing

    private void cmdSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSubmitActionPerformed
        String rut = txtRut.getText();
        String cemp = cmbEmpleo.getSelectedItem().toString();
        try{
            stm=conex.createStatement();
            ResultSet rs = stm.executeQuery("select cod_empleo from empleo where nom_empleo='"+cemp+"'");
            rs.next();
            cemp=rs.getString(1);
        }catch(SQLException ex){
                JOptionPane.showMessageDialog(null,ex,"conexion",3);
        }
        String nom = txtNombre.getText();
        String tipo;
        if (rbtAdmin.isSelected()){
            tipo= "A";
        }else{
            tipo= "E";
        }
        String fn = txtFono.getText();
        String email = txtEmail.getText();
        String he = txtHE.getText();
        String hs = txtHS.getText();
        if (!(rut.equals("")||(cemp.equals(""))||(nom.equals(""))||(fn.equals(""))||(email.equals(""))||(he.equals(""))||(hs.equals("")))){
            if (validaRut(rut)&&validarMail(email)){

            String sql= "insert into empleado values('" +rut+ "'," +cemp+ ",'" +nom+ "','" +tipo+ "'," +fn+ ",'" +email+ "','" +he+ "','" +hs+"')";
            String al;
            if (modo==1) {
                al= "Añadido Correctamente";
            }else{
                txtRut.setEditable(false);
                sql="update empleado set Empleo_cod_empleo="+cemp+", nombre='"+nom+
                            "', tipo='"+tipo+"', fono='"+fn+"', email='"+email+"', hora_entrada='"+he+"', hora_salida='"+hs+"' where Rut='"+rut+"'";
                al="Modificado Correctamente";

            }

            try{
                stm=conex.createStatement();
                stm.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, al,"conexion",3);
                m.setEnabled(true);
                m.mostrarTablaEmp();
                dispose();
            }catch(SQLException ex){
                JOptionPane.showMessageDialog(null,ex,"conexion",3);
            }
            }else if (validaRut(rut)){
                JOptionPane.showMessageDialog(null, "El Email no es válido","Atención",3);
            }else{JOptionPane.showMessageDialog(null, "El Rut no es válido","Atención",3);}
        }else{JOptionPane.showMessageDialog(null, "Todos los campos son Obligatorios","Atención",3);}
    }//GEN-LAST:event_cmdSubmitActionPerformed

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        char C = evt.getKeyChar();
        if (!(Character.isAlphabetic(C)||Character.isSpaceChar(C))){
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Emp().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbEmpleo;
    private javax.swing.JButton cmdCancelar;
    private javax.swing.JButton cmdSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBombre;
    private javax.swing.JLabel lblContacto;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmpleo;
    private javax.swing.JLabel lblFono;
    private javax.swing.JLabel lblHe;
    private javax.swing.JLabel lblHs;
    private javax.swing.JLabel lblRut;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JRadioButton rbtAdmin;
    private javax.swing.JRadioButton rbtEmp;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JFormattedTextField txtFono;
    private javax.swing.JFormattedTextField txtHE;
    private javax.swing.JFormattedTextField txtHS;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRut;
    // End of variables declaration//GEN-END:variables
}
