/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.CardLayout;
import java.awt.Color;
import java.util.HashSet;
import java.util.Set;
import javax.swing.*;
import java.sql.*;
import java.text.DateFormat;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.util.*;
import java.*;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author kris
 */
public class VerSolicitudes extends javax.swing.JFrame {
    Connection conex=null;
    Statement stm=null;
    private TableRowSorter trsfiltro;
    Menu m;
    /**
     * Creates new form VerSolicitudes
     */
    public VerSolicitudes() {
        initComponents();
        
    }
    public VerSolicitudes(Menu menu) {
        conectar();
        initComponents();
        mostrarTabla();
        this.m=menu;
    }
    public void conectar(){
        String url= "jdbc:mysql://localhost:3306/ttdb";
        String Usuario= "root";
        String Pass= "123456";
        try{
            conex=DriverManager.getConnection(url,Usuario,Pass);
            //JOptionPane.showMessageDialog(null,"conectado" ,"conexion",1);
        }catch (Exception ex){
            System.out.println(ex);
        }
    }
    public void mostrarTabla(){
        try{
            stm=conex.createStatement();
            jTable1.removeAll();
            DateFormat dateFormat1 = new SimpleDateFormat("yyyy-MM-dd");
            Date date = new Date();
            ResultSet rs = stm.executeQuery("select cod_soli,nombre,rut_soli,asunto,detalle,estado from solicitud_prestamo"); //hacer select de tabla solicitudes

            DefaultTableModel mod =(DefaultTableModel)jTable1.getModel();
            mod.setRowCount(0);
            
            while(rs.next()){
                Object data[]={rs.getString("cod_soli"),rs.getString("nombre"),rs.getString("rut_soli"),rs.getString("asunto"),rs.getString("estado"),rs.getString("detalle")};
                //Object data[]={rs.getString("rut"),rs.getShort("Empleo_cod_empleo"),rs.getString("nombre"),rs.getString("tipo"),rs.getString("fono"),rs.getString("email"),rs.getString("hora_entrada"),rs.getString("hora_salida")};

                mod.addRow(data);
            }
            jTable1.getColumnModel().getColumn(5).setMaxWidth(0);

            jTable1.getColumnModel().getColumn(5).setMinWidth(0);

            jTable1.getColumnModel().getColumn(5).setPreferredWidth(0);
            //JOptionPane.showMessageDialog(null, "selec"+dateFormat1.format(date),"conexion",3);
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "selec"+ex,"conexion",3);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cmdVolver = new javax.swing.JButton();
        cmdIngresar = new javax.swing.JButton();
        cmdModificar = new javax.swing.JButton();
        cmdAsig = new javax.swing.JButton();
        cmdDetalle = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Juan Perez", "10862755-7", "Bienvenida", "Revisada", null},
                {"2", "Carlos Santana", "19974002-4", "Despedida", "Revisada", null},
                {"3", "Ivan Salas", "15067621-5", "Celebración", "Pendiente", null},
                {"4", "Pedro Colina", "20848655-4", "Certificaión", "Pendiente", null}
            },
            new String [] {
                "Código", "Solicitante", "Rut", "Asunto", "Estado", "Detalle"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        cmdVolver.setText("volver");
        cmdVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdVolverActionPerformed(evt);
            }
        });

        cmdIngresar.setText("ingresar nueva");
        cmdIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdIngresarActionPerformed(evt);
            }
        });

        cmdModificar.setText("modificar");
        cmdModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdModificarActionPerformed(evt);
            }
        });

        cmdAsig.setText("Asignar solicitudes");
        cmdAsig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAsigActionPerformed(evt);
            }
        });

        cmdDetalle.setText("Detalles");
        cmdDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdDetalleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cmdVolver)
                        .addGap(18, 18, 18)
                        .addComponent(cmdIngresar)
                        .addGap(18, 18, 18)
                        .addComponent(cmdModificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmdAsig)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmdDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdAsig, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdModificarActionPerformed
        int ind= jTable1.getSelectedRow();
        DefaultTableModel mod =(DefaultTableModel)jTable1.getModel();
        
        String cod= mod.getValueAt(ind, 0).toString();
        String nom= mod.getValueAt(ind, 1).toString();
        String rut= mod.getValueAt(ind, 2).toString();
        String asu= mod.getValueAt(ind, 3).toString();
        String est= mod.getValueAt(ind, 4).toString();
        String det= mod.getValueAt(ind, 5).toString();
        Solicitud nuevaSoli = new Solicitud(this,cod,nom,rut,asu,est,det);
        nuevaSoli.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_cmdModificarActionPerformed

    private void cmdIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdIngresarActionPerformed
        Solicitud nuevaSoli=new Solicitud(this);
        nuevaSoli.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_cmdIngresarActionPerformed

    private void cmdVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdVolverActionPerformed
        m.setEnabled(true);
        dispose();
    }//GEN-LAST:event_cmdVolverActionPerformed

    private void cmdAsigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAsigActionPerformed
        AsigSolicitud asigSoli = new AsigSolicitud(this);
        asigSoli.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_cmdAsigActionPerformed

    private void cmdDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdDetalleActionPerformed
        DetalleSoli detalle = new DetalleSoli(this);
        detalle.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_cmdDetalleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerSolicitudes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerSolicitudes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerSolicitudes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerSolicitudes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerSolicitudes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdAsig;
    private javax.swing.JButton cmdDetalle;
    private javax.swing.JButton cmdIngresar;
    private javax.swing.JButton cmdModificar;
    private javax.swing.JButton cmdVolver;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
